[package]
name = "sunshine_indra"
version = "0.1.0"
edition = "2021"

[dependencies]
indradb-lib = { version = "2", features = ["rocksdb-datastore"] }
serde_json = "1.0.68"
uuid = { version = "0.8", features = ["v4"] }
thiserror = "1.0.30"
serde = { version = "1", features = ["derive"] }
